package com.notdoppler.core.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006781)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFBAEAFF)
val md_theme_light_onPrimaryContainer = Color(0xFF001F29)
val md_theme_light_secondary = Color(0xFFAE2F34)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDAD8)
val md_theme_light_onSecondaryContainer = Color(0xFF410006)
val md_theme_light_tertiary = Color(0xFF006A62)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF61F9E9)
val md_theme_light_onTertiaryContainer = Color(0xFF00201D)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFAFCFF)
val md_theme_light_onBackground = Color(0xFF001F2A)
val md_theme_light_surface = Color(0xFFFAFCFF)
val md_theme_light_onSurface = Color(0xFF001F2A)
val md_theme_light_surfaceVariant = Color(0xFFDCE4E8)
val md_theme_light_onSurfaceVariant = Color(0xFF40484C)
val md_theme_light_outline = Color(0xFF70787D)
val md_theme_light_inverseOnSurface = Color(0xFFE1F4FF)
val md_theme_light_inverseSurface = Color(0xFF003547)
val md_theme_light_inversePrimary = Color(0xFF5FD4FE)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006781)
val md_theme_light_outlineVariant = Color(0xFFC0C8CC)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF5FD4FE)
val md_theme_dark_onPrimary = Color(0xFF003544)
val md_theme_dark_primaryContainer = Color(0xFF004D62)
val md_theme_dark_onPrimaryContainer = Color(0xFFBAEAFF)
val md_theme_dark_secondary = Color(0xFFFFB3B0)
val md_theme_dark_onSecondary = Color(0xFF68000F)
val md_theme_dark_secondaryContainer = Color(0xFF8C1520)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDAD8)
val md_theme_dark_tertiary = Color(0xFF3ADCCC)
val md_theme_dark_onTertiary = Color(0xFF003732)
val md_theme_dark_tertiaryContainer = Color(0xFF005049)
val md_theme_dark_onTertiaryContainer = Color(0xFF61F9E9)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001F2A)
val md_theme_dark_onBackground = Color(0xFFBFE9FF)
val md_theme_dark_surface = Color(0xFF001F2A)
val md_theme_dark_onSurface = Color(0xFFBFE9FF)
val md_theme_dark_surfaceVariant = Color(0xFF40484C)
val md_theme_dark_onSurfaceVariant = Color(0xFFC0C8CC)
val md_theme_dark_outline = Color(0xFF8A9296)
val md_theme_dark_inverseOnSurface = Color(0xFF001F2A)
val md_theme_dark_inverseSurface = Color(0xFFBFE9FF)
val md_theme_dark_inversePrimary = Color(0xFF006781)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF5FD4FE)
val md_theme_dark_outlineVariant = Color(0xFF40484C)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF87CEEB)